from abc import ABC, abstractmethod
import numpy as np


class DummyData(ABC):
    @abstractmethod
    def transform(self, x):
        """
        Transform the data from parameter space to real space
        Args:
            x: an array of coordinates in parameter space. The size of the last dimension
                must correspond to the dimensionality of the manifold

        Returns:
            The data points in real space. The shape is (shape(x)[:-1], N) where N is the number of dimensions of the
            embedded space
        """
        pass

    @abstractmethod
    def sample_parameters(self, n_points):
        """
        Sample parameters randomly from parameter space
        Returns: The sampled parameters
        """

    def sample(self, n_points, noise):
        """
        Randomly sample data from manifold
        Args:
            n_points:
            noise:

        Returns:
            x: the parameters used to generate the manifold
            data: The data points in real space

        """
        x = self.sample_parameters(n_points)
        data = self.transform(x)
        if noise > 0:
            data += np.random.normal(size=data.shape, scale=noise)
        return x, data


class LinearSpiral(DummyData):
    def __init__(self, start: float = 1, end: float = 3, alpha: float = 1.0):
        self.start = start
        self.end = end
        self.alpha = alpha

    def transform(self, x):
        x_coord = np.cos(2 * np.pi * x[..., 0]) * self.alpha * x[..., 0]
        y_coord = np.sin(2 * np.pi * x[..., 0]) * self.alpha * x[..., 0]
        return np.stack((x_coord, y_coord), axis=-1)

    def sample_parameters(self, n_points):
        return self.start + (self.end - self.start) * np.random.random(size=(n_points, 1))


class LinearSpiralNonUniform(LinearSpiral):
    def __init__(self):
        super().__init__(start=1, end=3, alpha=1)
        self.xs = np.linspace(-1, 1, 200)
        self.ys = self.cdf(self.xs)

    def sample_parameters(self, n_points):
        uni = np.random.random(size=(n_points, 1))  # uniformly random points from 0 to 1
        return 2 + np.interp(uni, self.ys, self.xs)

    @classmethod
    def pdf(cls, x):
        """PDF of the probability distribution in sampling space"""
        return 1 / 2 + 3 * (x - 2) * np.exp(-(3 * (x - 2)) ** 2)

    @classmethod
    def cdf(cls, x):
        """CDF of x-2, for simplicity"""
        return 1 / 2 * (x + 1) - 1 / 6 * np.exp(-(3 * x) ** 2)


class SwissRoll(DummyData):
    def __init__(self, start: float = 1, end: float = 3, alpha: float = 1.0, z=3):
        """

        Args:
            start:
            end:
            alpha: the coiling speed. If larger, the spiral is looser
            z: Width of the roll
        """
        self.start = start
        self.end = end
        self.alpha = alpha
        self.z = z

    def transform(self, x):
        x_coord = np.cos(2 * np.pi * x[..., 0]) * self.alpha * x[..., 0]
        y_coord = np.sin(2 * np.pi * x[..., 0]) * self.alpha * x[..., 0]
        return np.stack((x_coord, y_coord, x[..., 1]), axis=-1)

    def sample_parameters(self, n_points):
        xs = self.start + (self.end - self.start) * np.random.random(size=n_points)
        zs = self.z * np.random.random(size=n_points)
        return np.stack((xs, zs), axis=-1)

    @classmethod
    def unroll(cls, data, alpha: float):
        """Unroll swiss roll as generated by SwissRoll.sample()

        Args:
            data: swiss roll data
            alpha: The alpha parameter used for generation

        Returns:
            a Nx3 numpy array. The first two columns are the parameters t (angle) and z (height) of the swiss roll
            The third column is the displacement orthogonal to the roll
        """
        x = data[:, 0]
        y = data[:, 1]
        z = data[:, 2]

        angle = np.arctan2(y, x) % (2 * np.pi)  # argument, in the range of [0, 2*pi]
        r = np.sqrt(x ** 2 + y ** 2)
        r0 = alpha * angle / (2 * np.pi)  # radius corresponding to the angle in the first winding of the spiral
        winding = np.round((r - r0) / alpha, 0)  # best guess as to which winding the point is
        t = angle / (2 * np.pi) + winding
        h = r - alpha * t  # displacement orthogonal to the swiss roll

        return np.stack((t, z, h), axis=-1)


class SwissRollNonUniform(SwissRoll):
    """Swiss roll with parameters sampled non-uniformly"""

    def __init__(self, z=50):
        super().__init__(start=3 / 4, end=9 / 4, alpha=2 * np.pi, z=z)

    def sample_parameters(self, n_points):
        """Sample parameters from a non-uniform distribution. For simplicity, we use a rejection method, which is not
        very efficient, especially if the pdf varies over different orders of magnitude"""
        result = np.empty((0, 2))
        while len(result) < n_points:
            ts = self.start + (self.end - self.start) * np.random.random(size=2 * n_points)
            zs = self.z * np.random.random(size=2 * n_points)
            ps = 3 * np.random.random(size=2 * n_points)  # go up to 2, which is the maximal value of f

            select = ps < self.pdf(ts, zs)
            result = np.concatenate((result, np.stack((ts, zs), axis=-1)[select]))

        return result[:n_points]

    @classmethod
    def pdf(cls, t, z):
        """pdf (non-normalized) of the parameter distribution"""
        return (1 + 2 * np.exp(-1 / 2 * (8 * (t - 1)) ** 2 - 1 / 2 * ((z - 15) / 7) ** 2)) * \
            (1 - np.exp(-1 / 2 * (8 * (t - 1.5)) ** 2 - 1 / 2 * ((z - 20) / 7) ** 2)) * \
            np.where(t < 7 / 4, 1, 0.5 - 3 / 4 * (t - 7 / 4))


class CShape(DummyData):
    def __init__(self, radius: float = 1, start: float = 0, end: float = 0.5):
        """
        Dummy data in the shape of the letter C
        """
        self.radius = radius
        self.start = start
        self.end = end

    def sample_parameters(self, n_points):
        return self.start + (self.end - self.start) * np.random.random(size=(n_points, 1))

    def transform(self, x):
        x_coord = np.cos(2 * np.pi * x[..., 0])
        y_coord = np.sin(2 * np.pi * x[..., 0])
        return np.stack((x_coord, y_coord), axis=-1)


class TwoClusters:
    def __init__(self):
        pass

    def sample(self, n_points, noise):
        n1 = int(n_points / 2)
        n2 = n_points - n1
        c = CShape(start=-0.1, end=0.6)
        _, c1 = c.sample(n1, noise)
        _, c2 = c.sample(n2, noise)
        c2[:, 1] *= (-1)
        c2[:, 0] += 1
        c1[:, 1] += 0.3
        c2[:, 1] -= 0.3
        cluster_idx = np.concatenate((np.repeat(0, n1), np.repeat(1, n2)))
        return cluster_idx, np.concatenate((c1, c2))

